INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('AMD', 'Sardar Vallabhbhai Patel International Airport', 'Ahmedabad', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('AKD', 'Akola Airport', 'Akola', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXU', 'Aurangabad Airport', 'Aurangabad', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BOM', 'Chhatrapati Shivaji International Airport', 'Mumbai', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PAB', 'Bilaspur Airport', 'Bilaspur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BHJ', 'Bhuj Airport', 'Bhuj', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXG', 'Belgaum Airport', 'Belgaum', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BDQ', 'Vadodara Airport', 'Baroda', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BHO', 'Raja Bhoj International Airport', 'Bhopal', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BHU', 'Bhavnagar Airport', 'Bhaunagar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('NMB', 'Daman Airport', 'Daman', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('GUX', 'Guna Airport', 'Guna', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('GOI', 'Dabolim Airport', 'Goa', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IDR', 'Devi Ahilyabai Holkar Airport', 'Indore', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('JLR', 'Jabalpur Airport', 'Jabalpur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('JGA', 'Jamnagar Airport', 'Jamnagar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXY', 'Kandla Airport', 'Kandla', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('HJR', 'Khajuraho Airport', 'Khajuraho', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('KLH', 'Kolhapur Airport', 'Kolhapur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXK', 'Keshod Airport', 'Keshod', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('NAG', 'Dr. Babasaheb Ambedkar International Airport', 'Nagpur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('ISK', 'Nashik Airport', 'Nasik Road', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PNQ', 'Pune Airport', 'Pune', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PBD', 'Porbandar Airport', 'Porbandar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('RAJ', 'Rajkot Airport', 'Rajkot', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('RPR', 'Raipur Airport', 'Raipur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SSE', 'Solapur Airport', 'Sholapur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('STV', 'Surat Airport', 'Surat', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('UDR', 'Maharana Pratap Airport', 'Udaipur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXV', 'Along Airport', 'Along', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXA', 'Agartala Airport', 'Agartala', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('AJL', 'Lengpui Airport', 'Aizwal', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXB', 'Bagdogra Airport', 'Baghdogra', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BBI', 'Biju Patnaik Airport', 'Bhubaneswar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('CCU', 'Netaji Subhash Chandra Bose International Airport', 'Kolkata', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('COH', 'Cooch Behar Airport', 'Cooch-behar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('DBD', 'Dhanbad Airport', 'Dhanbad', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('GAY', 'Gaya Airport', 'Gaya', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IMF', 'Imphal Airport', 'Imphal', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXW', 'Sonari Airport', 'Jamshedpur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('JRH', 'Jorhat Airport', 'Jorhat', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXH', 'Kailashahar Airport', 'Kailashahar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXS', 'Silchar Airport', 'Silchar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXI', 'North Lakhimpur Airport', 'Lilabari', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('DIB', 'Dibrugarh Airport', 'Mohanbari', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('MZU', 'Muzaffarpur Airport', 'Mazuffarpur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PAT', 'Lok Nayak Jayaprakash Airport', 'Patina', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXR', 'Birsa Munda Airport', 'Ranchi', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('RRK', 'Rourkela Airport', 'Rourkela', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('VTZ', 'Vishakhapatnam Airport', 'Vishakhapatnam', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('ZER', 'Ziro Airport', 'Zero', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('AGR', 'Agra Airport', 'Agra', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXD', 'Allahabad Airport', 'Allahabad', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('ATQ', 'Sri Guru Ram Dass Jee International Airport', 'Amritsar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BKB', 'Nal Airport', 'Bikaner', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('VNS', 'Lal Bahadur Shastri Airport', 'Varanasi', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('KUU', 'Kullu Manali Airport', 'Kulu', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXC', 'Chandigarh Airport', 'Chandigarh', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('KNU', 'Kanpur Airport', 'Kanpur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('DED', 'Dehradun Airport', 'Dehra Dun', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('DEL', 'Indira Gandhi International Airport', 'Delhi', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('GWL', 'Gwalior Airport', 'Gwalior', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('HSS', 'Hissar Airport', 'Hissar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('JDH', 'Jodhpur Airport', 'Jodhpur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('JAI', 'Jaipur International Airport', 'Jaipur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('JSA', 'Jaisalmer Airport', 'Jaisalmer', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXJ', 'Jammu Airport', 'Jammu', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('KTU', 'Kota Airport', 'Kota', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('LUH', 'Ludhiana Airport', 'Ludhiaha', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXL', 'Leh Kushok Bakula Rimpochee Airport', 'Leh', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('LKO', 'Chaudhary Charan Singh International Airport', 'Lucknow', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXP', 'Pathankot Airport', 'Pathankot', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PGH', 'Pantnagar Airport', 'Nainital', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SXR', 'Sheikh ul Alam Airport', 'Srinagar', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('TNI', 'Satna Airport', 'Satna', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('AGX', 'Agatti Airport', 'Agatti Island', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BLR', 'Kempegowda International Airport', 'Bangalore', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BEP', 'Bellary Airport', 'Bellary', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('VGA', 'Vijayawada Airport', 'Vijayawada', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('CJB', 'Coimbatore International Airport', 'Coimbatore', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('COK', 'Cochin International Airport', 'Kochi', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('CCJ', 'Calicut International Airport', 'Calicut', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('CDP', 'Kadapa Airport', 'Cuddapah', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('BPM', 'Begumpet Airport', 'Hyderabad', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXM', 'Madurai Airport', 'Madurai', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXE', 'Mangalore International Airport', 'Mangalore', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('MAA', 'Chennai International Airport', 'Madras', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXZ', 'Vir Savarkar International Airport', 'Port Blair', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PNY', 'Pondicherry Airport', 'Pendicherry', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('RJA', 'Rajahmundry Airport', 'Rajahmundry', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SXV', 'Salem Airport', 'Salem', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('TIR', 'Tirupati Airport', 'Tirupeti', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('TRZ', 'Tiruchirapally Civil Airport Airport', 'Tiruchirappalli', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('TRV', 'Trivandrum International Airport', 'Trivandrum', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('DIU', 'Diu Airport', 'Diu', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('HBX', 'Hubli Airport', 'Hubli', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SHL', 'Shillong Airport', 'Shillong', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('GAU', 'Lokpriya Gopinath Bordoloi International Airport', 'Guwahati', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('DMU', 'Dimapur Airport', 'Dimapur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('TEZ', 'Tezpur Airport', 'Tezpur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('GOP', 'Gorakhpur Airport', 'Gorakhpur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('DHM', 'Kangra Airport', 'Kangra', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('NDC', 'Nanded Airport', 'Nanded', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SLV', 'Shimla Airport', 'Shimla', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('MYQ', 'Mysore Airport', 'Mysore', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('IXT', 'Pasighat Airport', 'Pasighat', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('RTC', 'Ratnagiri Airport', 'Mirjole', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('RDP', 'Kazi Nazrul Islam Airport', 'Durgapur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PUT', 'Sri Sathya Sai Airport', 'Puttaparthi', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('HYD', 'Rajiv Gandhi International Airport', 'Hyderabad', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('TEI', 'Tezu Airport', 'Tezu', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('AIP', 'Adampur Airport', 'Adampur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('SAG', 'Shirdi Airport', 'Shirdi', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('PYB', 'Jeypore Airport', 'Jeypore', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('KQH', 'Kishangarh Airport', 'Ajmer', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('CNN', 'Kannur International Airport', 'Kannur', 'India');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `country`) VALUES ('LTU', 'Latur Airport', 'Latur', 'India');
