
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('DEL', 'Indira Gandhi International Airport', 'New Delhi', 'Delhi', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai', 'Maharashtra', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('BLR', 'Kempegowda International Airport', 'Bengaluru', 'Karnataka', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('HYD', 'Rajiv Gandhi International Airport', 'Hyderabad', 'Telangana', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('MAA', 'Chennai International Airport', 'Chennai', 'Tamil Nadu', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CCU', 'Netaji Subhas Chandra Bose International Airport', 'Kolkata', 'West Bengal', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('AMD', 'Sardar Vallabhbhai Patel International Airport', 'Ahmedabad', 'Gujarat', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('PNQ', 'Pune Airport', 'Pune', 'Maharashtra', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('GOI', 'Manohar International Airport', 'North Goa', 'Goa', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('DAB', 'Goa International Airport', 'South Goa', 'Goa', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('COK', 'Cochin International Airport', 'Kochi', 'Kerala', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('TRV', 'Trivandrum International Airport', 'Thiruvananthapuram', 'Kerala', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CJB', 'Coimbatore International Airport', 'Coimbatore', 'Tamil Nadu', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('TRZ', 'Tiruchirappalli International Airport', 'Trichy', 'Tamil Nadu', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('IXM', 'Madurai Airport', 'Madurai', 'Tamil Nadu', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('IXE', 'Mangaluru International Airport', 'Mangaluru', 'Karnataka', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('VGA', 'Vijayawada Airport', 'Vijayawada', 'Andhra Pradesh', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('VTZ', 'Visakhapatnam Airport', 'Visakhapatnam', 'Andhra Pradesh', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('BBI', 'Biju Patnaik International Airport', 'Bhubaneswar', 'Odisha', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('PAT', 'Jay Prakash Narayan Airport', 'Patna', 'Bihar', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('GAU', 'Lokpriya Gopinath Bordoloi Airport', 'Guwahati', 'Assam', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('IXB', 'Bagdogra Airport', 'Siliguri', 'West Bengal', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('IXR', 'Birsa Munda Airport', 'Ranchi', 'Jharkhand', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('RPR', 'Swami Vivekananda Airport', 'Raipur', 'Chhattisgarh', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('LKO', 'Chaudhary Charan Singh Airport', 'Lucknow', 'Uttar Pradesh', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('VNS', 'Lal Bahadur Shastri Airport', 'Varanasi', 'Uttar Pradesh', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('JAI', 'Jaipur International Airport', 'Jaipur', 'Rajasthan', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('UDR', 'Maharana Pratap Airport', 'Udaipur', 'Rajasthan', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('JDH', 'Jodhpur Airport', 'Jodhpur', 'Rajasthan', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('ATQ', 'Sri Guru Ram Dass Jee Airport', 'Amritsar', 'Punjab', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CDG', 'Chandigarh Airport', 'Chandigarh', 'Chandigarh', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('DED', 'Jolly Grant Airport', 'Dehradun', 'Uttarakhand', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('SXR', 'Sheikh ul-Alam Airport', 'Srinagar', 'Jammu & Kashmir', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('IXJ', 'Jammu Airport', 'Jammu', 'Jammu & Kashmir', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('RAJ', 'Rajkot Airport', 'Rajkot', 'Gujarat', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('BHJ', 'Bhuj Airport', 'Bhuj', 'Gujarat', '');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('DXB', 'Dubai International Airport', 'Dubai', '', 'UAE');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('AUH', 'Zayed International Airport', 'Abu Dhabi', '', 'UAE');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('SHJ', 'Sharjah International Airport', 'Sharjah', '', 'UAE');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('DOH', 'Hamad International Airport', 'Doha', '', 'Qatar');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('MCT', 'Muscat International Airport', 'Muscat', '', 'Oman');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('RUH', 'King Khalid International Airport', 'Riyadh', '', 'Saudi Arabia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('JED', 'King Abdulaziz International Airport', 'Jeddah', '', 'Saudi Arabia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('DMM', 'King Fahd International Airport', 'Dammam', '', 'Saudi Arabia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('KWI', 'Kuwait International Airport', 'Kuwait City', '', 'Kuwait');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('BAH', 'Bahrain International Airport', 'Manama', '', 'Bahrain');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('SIN', 'Changi International Airport', 'Singapore', '', 'Singapore');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('BKK', 'Suvarnabhumi International Airport', 'Bangkok', '', 'Thailand');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('DMK', 'Don Mueang International Airport', 'Bangkok', '', 'Thailand');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('HKT', 'Phuket International Airport', 'Phuket', '', 'Thailand');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('KUL', 'Kuala Lumpur International Airport', 'Kuala Lumpur', '', 'Malaysia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('PEN', 'Penang International Airport', 'Penang', '', 'Malaysia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CGK', 'Soekarno–Hatta International Airport', 'Jakarta', '', 'Indonesia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('DPS', 'Ngurah Rai International Airport', 'Bali', '', 'Indonesia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('MNL', 'Ninoy Aquino International Airport', 'Manila', '', 'Philippines');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('HAN', 'Noi Bai International Airport', 'Hanoi', '', 'Vietnam');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('SGN', 'Tan Son Nhat International Airport', 'Ho Chi Minh City', '', 'Vietnam');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CMB', 'Bandaranaike International Airport', 'Colombo', '', 'Sri Lanka');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('KTM', 'Tribhuvan International Airport', 'Kathmandu', '', 'Nepal');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('DAC', 'Hazrat Shahjalal International Airport', 'Dhaka', '', 'Bangladesh');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CGP', 'Shah Amanat International Airport', 'Chittagong', '', 'Bangladesh');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('MLE', 'Velana International Airport', 'Male', '', 'Maldives');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('ISB', 'Islamabad International Airport', 'Islamabad', '', 'Pakistan');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('LHE', 'Allama Iqbal International Airport', 'Lahore', '', 'Pakistan');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('KHI', 'Jinnah International Airport', 'Karachi', '', 'Pakistan');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('LHR', 'Heathrow Airport', 'London', '', 'United Kingdom');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('LGW', 'Gatwick Airport', 'London', '', 'United Kingdom');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CDG', 'Charles de Gaulle Airport', 'Paris', '', 'France');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('ORY', 'Orly Airport', 'Paris', '', 'France');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('AMS', 'Schiphol Airport', 'Amsterdam', '', 'Netherlands');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('FRA', 'Frankfurt Airport', 'Frankfurt', '', 'Germany');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('MUC', 'Munich Airport', 'Munich', '', 'Germany');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('FCO', 'Leonardo da Vinci International Airport', 'Rome', '', 'Italy');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('MXP', 'Milan Malpensa Airport', 'Milan', '', 'Italy');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('MAD', 'Adolfo Suárez Madrid–Barajas Airport', 'Madrid', '', 'Spain');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('BCN', 'Barcelona–El Prat Airport', 'Barcelona', '', 'Spain');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('ZRH', 'Zurich Airport', 'Zurich', '', 'Switzerland');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('VIE', 'Vienna International Airport', 'Vienna', '', 'Austria');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('IST', 'Istanbul Airport', 'Istanbul', '', 'Turkey');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('JFK', 'John F Kennedy International Airport', 'New York', '', 'USA');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('EWR', 'Newark Liberty International Airport', 'Newark', '', 'USA');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('LAX', 'Los Angeles International Airport', 'Los Angeles', '', 'USA');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('SFO', 'San Francisco International Airport', 'San Francisco', '', 'USA');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('ORD', 'O\'Hare International Airport', 'Chicago', '', 'USA');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('IAD', 'Washington Dulles International Airport', 'Washington DC', '', 'USA');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('YYZ', 'Toronto Pearson International Airport', 'Toronto', '', 'Canada');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('YVR', 'Vancouver International Airport', 'Vancouver', '', 'Canada');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('YUL', 'Montréal–Trudeau International Airport', 'Montreal', '', 'Canada');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('GRU', 'São Paulo–Guarulhos International Airport', 'São Paulo', '', 'Brazil');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('EZE', 'Ministro Pistarini International Airport', 'Buenos Aires', '', 'Argentina');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('JNB', 'O. R. Tambo International Airport', 'Johannesburg', '', 'South Africa');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CPT', 'Cape Town International Airport', 'Cape Town', '', 'South Africa');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CAI', 'Cairo International Airport', 'Cairo', '', 'Egypt');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('NBO', 'Jomo Kenyatta International Airport', 'Nairobi', '', 'Kenya');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('ADD', 'Addis Ababa Bole International Airport', 'Addis Ababa', '', 'Ethiopia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CMN', 'Mohammed V International Airport', 'Casablanca', '', 'Morocco');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('SYD', 'Sydney Kingsford Smith Airport', 'Sydney', '', 'Australia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('MEL', 'Melbourne Airport', 'Melbourne', '', 'Australia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('BNE', 'Brisbane Airport', 'Brisbane', '', 'Australia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('PER', 'Perth Airport', 'Perth', '', 'Australia');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('AKL', 'Auckland International Airport', 'Auckland', '', 'New Zealand');
INSERT INTO `airports` (`airport_code`, `airport_name`, `city`, `state_UT`, `country`) VALUES ('CHC', 'Christchurch International Airport', 'Christchurch', '', 'New Zealand');
